### PR TITLE
DOCSP-34755 Add Connection String Option Note

### PR DESCRIPTION
**Pull request by ianf-mongodb**
## DESCRIPTION

Add details to the MongoDB connection string page that Relational Migrator supports all connection string options except appname when connecting to MongoDB.

## STAGING

https://preview-mongodbianfmongodb.gatsbyjs.io/docs-relational-migrator/DOCSP-34755/connection-strings/mongodb-database-connection-strings/

## JIRA

https://jira.mongodb.org/browse/DOCSP-34755

## BUILD LOG

https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=6579fe387a5cb5fef5d1efe2

## Self-Review Checklist

- [ ] Is this free of any warnings or errors in the RST?
- [ ] Is this free of spelling errors?
- [ ] Is this free of grammatical errors?
- [ ] Is this free of staging / rendering issues?
- [ ] Are all the links working?

## External Review Requirements

[What's expected of an external reviewer?](https://wiki.corp.mongodb.com/display/DE/Reviewing+Guidelines+for+the+MongoDB+Server+Documentation)

### CODE REVIEW

**Review by jason-price-mongodb — APPROVED** [review]
@ianf-mongodb LGTM. Cheers.

**Comment by ianf-mongodb** [comment]
Hi @tomhollander, this was a question in the slack channel a couple weeks ago. I wanted to add reference since we did not explicitly call this out on the initial draft. Thanks!

**Comment by tomhollander** [comment]
I don't understand why we need to communicate this to users? This is largely for our own telemetry purposes.

**Comment by ianf-mongodb** [comment]
> I don't understand why we need to communicate this to users? This is largely for our own telemetry purposes.

Its possible they might provided a connection string with `?appname=xxxx` and be confused. Although its unlikely its a technical limitation. The message is more so to reinforce the fact that any connection string option is available when your connecting to MongoDB. @tomhollander

**Comment by tomhollander** [comment]
I'm not convinced this detail will help; it may just confuse people more. I doubt many users ever use or have heard of this parameter.

**Comment by ianf-mongodb** [comment]
> I'm not convinced this detail will help; it may just confuse people more. I doubt many users ever use or have heard of this parameter.

@tomhollander Isnt it a valid use case to look at system logs for what Migrator is doing on a MongoDB server? You would need to know that the connection appName was Relational Migrator to check the statements run on your instance. I understand its a low % use case but there is still the possibility that a user may include it in their connection URI and be surprised if not documented.

**Review by tomhollander — APPROVED** [review]

**Pull request merged**
