### PR TITLE
DOCSP-36712 1.4.6 Release Notes

### PR DESCRIPTION
**Pull request by ianf-mongodb**
## DESCRIPTION

RM 1.4.6 Release Notes.

## STAGING

https://preview-mongodbianfmongodb.gatsbyjs.io/docs-relational-migrator/DOCSP-36712/release-notes/

## JIRA

https://jira.mongodb.org/browse/DOCSP-36712

## BUILD LOG

https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=65cbe077cbcd269fa5e4264c

## Self-Review Checklist

- [ ] Is this free of any warnings or errors in the RST?
- [ ] Is this free of spelling errors?
- [ ] Is this free of grammatical errors?
- [ ] Is this free of staging / rendering issues?
- [ ] Are all the links working?

## External Review Requirements

[What's expected of an external reviewer?](https://wiki.corp.mongodb.com/display/DE/Reviewing+Guidelines+for+the+MongoDB+Server+Documentation)

### CODE REVIEW

**Review by jmd-mongo — APPROVED** [review]
Thanks for these release notes, @ianf-mongodb! This one LGTM.

Thanks,
Joe

**Comment by ianf-mongodb** [comment]
@tomhollander This are ready for a quick look.

**Review by tomhollander — APPROVED** [review]

**Review by davidsoulmdb — APPROVED** [review]
I could not view the notes in the live preview build at all, however the underlying release notes text looks solid to me. Approved based purely on the text from my side and assuming they will be visible in the final build, but let me know if this is unexpected behavior.

**Comment by tomhollander** [comment]
> I could not view the notes in the live preview build at all, however the underlying release notes text looks solid to me. Approved based purely on the text from my side and assuming they will be visible in the final build, but let me know if this is unexpected behavior.

https://preview-mongodbianfmongodb.gatsbyjs.io/docs-relational-migrator/DOCSP-36712/release-notes/

**Pull request merged**
