### PR TITLE
DOCSP 34588 Update RM supported databases topic to cover SQL Server 2012

### PR DESCRIPTION
**Pull request by ltran-mdb2**
## DESCRIPTION

Update RM supported databases topic to cover SQL Server 2012

## STAGING

https://preview-mongodbltranmdb2.gatsbyjs.io/docs-relational-migrator/DOCSP-34588/supported-databases/

## JIRA

https://jira.mongodb.org/browse/DOCSP-34588

## BUILD LOG

https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=657b6bf57a5cb5fef53ca185

## Self-Review Checklist

- [x] Is this free of any warnings or errors in the RST?
- [x] Is this free of spelling errors?
- [x] Is this free of grammatical errors?
- [x] Is this free of staging / rendering issues?
- [x] Are all the links working?

## External Review Requirements

[What's expected of an external reviewer?](https://wiki.corp.mongodb.com/display/DE/Reviewing+Guidelines+for+the+MongoDB+Server+Documentation)

### CODE REVIEW

**Review by sarah-olson-mongodb — APPROVED** [review]
Thanks @ltran-mdb2, appreciate the update! 
LGTM

**Comment by tomhollander** [comment]
Note this PR clashes with the Sybase update, so be careful not to overwrite that one.

**Comment by ltran-mdb2** [comment]
Thanks for the heads up @tomhollander ! Would you be able to give this PR a tech review when you get a chance?

**Comment by tomhollander** [comment]
Thanks the content is all correct although I think the info in the blue banner would be better inline with the table or at least linked with an asterisk, as that extra info could easily be missed. The Sybase row currently has limitations listed in the Deployments column which isn't really the intent of that column either.

**Comment by ltran-mdb2** [comment]
HI @tomhollander I had some confusion over whether the limitation related to MongoDB editions were or SQL Server editions so I changed the formatting with what (I think) is the right understanding - could you take another look when you get a chance?

**Comment by tomhollander** [comment]
Thanks @ltran-mdb2. I'm not a fan of breaking SQL Server into two lines. Here's a suggestion to put this info in the Supported Versions column, that also cleans up the recent Sybase changes. cc @sarah-olson-mongodb @ianf-mongodb 

 Database | Supported Versions | Deployments 
--|--|--
Oracle | 12c and higher | Self hosted, AWS RDS
Microsoft SQL Server | 2012 and higher <br /> (Enterprise/Developer edition required for versions prior to 2016)| Self hosted, AWS RDS, Azure SQL Database
PostgreSQL | 10 and higher | Self hosted, AWS RDS/Aurora, Azure Database
MySQL | 5.7 and higher | Self hosted, AWS RDS/Aurora, Azure Database
Sybase ASE | 15 and higher <br />(Sybase IQ not supported) | Self hosted

**Comment by ltran-mdb2** [comment]
Just made the change you suggested @tomhollander ! I will create a separate ticket to update the Sybase row.

**Comment by tomhollander** [comment]
Thanks, I think this is an improvement.

**Pull request merged**
