### PR TITLE
DOCSP-38811 migrator 1.6.0 release notes

### PR DESCRIPTION
**Pull request by ltran-mdb2**
## DESCRIPTION

1.6.0 release notes

## STAGING

https://preview-mongodbltranmdb2.gatsbyjs.io/docs-relational-migrator/DOCSP-38811/release-notes/

## JIRA

https://jira.mongodb.org/browse/DOCSP-38811

## BUILD LOG

https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=662272b1132d178bc1c6b4fa

## Self-Review Checklist

- [ ] Is this free of any warnings or errors in the RST?
- [ ] Is this free of spelling errors?
- [ ] Is this free of grammatical errors?
- [ ] Is this free of staging / rendering issues?
- [ ] Are all the links working?

## External Review Requirements

[What's expected of an external reviewer?](https://wiki.corp.mongodb.com/display/DE/Reviewing+Guidelines+for+the+MongoDB+Server+Documentation)

### CODE REVIEW

**Review by sarah-olson-mongodb — COMMENTED** [review]
Nice work @ltran-mdb2! Thanks a ton for these updates. I know we are all over the place when we do release notes. Because these aren't auto generated, what do you think about taking a quick pass through the new features and tweak a bit? Aim would be to address the user, include complete sentences, and add a link when possible? @ianf-mongodb can help quickly determine which docs are ready with links.

**Comment by ltran-mdb2** [comment]
Thanks for your feedback @sarah-olson-mongodb ! Could you take another look when you get a chance? I reworded the line items and talked to Ian about new links - he said they the release notes with new links are still in review so he will add the links once they are published!

**Review by sarah-olson-mongodb — APPROVED** [review]
Thanks @ltran-mdb2! LGTM

**Comment by ltran-mdb2** [comment]
LGTM from Tom Hollander over slack

**Pull request merged**
